# Generated by Django 3.2.16 on 2025-04-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={},
        ),
        migrations.AddConstraint(
            model_name='myuser',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_user'),
        ),
    ]
