version: '3'

volumes:
  pg_data:
  static_volume:
  media_volume:
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: foodgram_backend
    depends_on:
      - db
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
  frontend:
    image: foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: foodgram_gateway
    env_file: .env
    volumes:
      - static_volume:/static/
      - media_volume:/media
      - ./docs/:/usr/share/nginx/html/api/docs/
    ports:
      - 8000:80
    depends_on:
      - backend